### ISSUE TITLE
Erro ao abrir o VREP

### ISSUE THREAD

**Issue by WesleyPizetta** [filRocha/rosiChallenge-sbai2019#4]
Ao abrir o VREP, ele inicializa e seus plugins começam a carregar. Porém, antes mesmo de abrir, ele fecha e uma mensagem de erro aparece no console:

linha 33: 12654 Instrução ilegal      (imagem do núcleo gravada) "$dirname/$appname" "${PARAMETERS[@]}"

Gostaria de pedir ajuda para encontrar uma solução para tal problema. Obrigado pela atenção!

**Comment by rcmurakami** [comment]
Tive o mesmo problema, para conseguir rodar tive que instalar uma versão anterior do vrep, a 3.6.1

**Comment by WesleyPizetta** [comment]
> Tive o mesmo problema, para conseguir rodar tive que instalar uma versão anterior do vrep, a 3.6.1

Muito obrigado!
